version: "3"

tasks:
  default:
    silent: true
    cmds:
      - task --list --sort none

  bootstrap:
    desc: Initialize development environment
    cmds:
      - uv python install 3.11
      - uv venv
      - uv sync
      - uv run pre-commit install

  tests:
    desc: Run tests
    cmds:
      - uv run pytest
