
sources:
  source-1:
    connection:
      host: "127.0.0.1"
      username: "CHANGEME!"
      password: "CHANGEME!"
      driver: "sqlite"

    tables:
      schema.table_a: datetime_column
      schema.table_b: timestamp_column
      schema.table_a:  # if None, it will download all data
  
  # adds as many sources as you would like
  # ...